ARKITSCENE_SCANNET= {
'bed': 'bed',
'cabinet': 'cabinet',
'refrigerator': 'refrigerator',
'table': 'table',
'chair': 'chair',
'sink': 'sink',
'stove': 'stove',
'oven': 'oven',
'washer': 'washing machine',
'shelf': 'shelf',
'tv_monitor': 'tv',
'bathtub': 'bathtub',
'toilet': 'toilet',
'sofa': 'sofa',
'stool': 'stool',
'fireplace': 'fireplace',
'build_in_cabinet': 'cabinet',
'dishwasher': 'dishwasher',
'stairs': 'stairs'
}


MULTISCAN_SCANNET = {
    "wall": "wall",
    "door": "door",
    "slippers": "shoe",
    "mop": "broom",
    "rug": "rug",
    "floor": "floor",
    "basin": "sink",
    "basin_stand": "sink",
    "bucket": "bucket",
    "shower": "shower",
    "water_tank": "container",
    "beam": "wood beam",
    "pillar": "pillar",
    "ceiling": "ceiling",
    "sink": "sink",
    "toilet": "toilet",
    "cabinet": "cabinet",
    "remove": "object",
    "towel": "towel",
    "pillow": "pillow",
    "sofa": "sofa",
    "footstool": "footstool",
    "picture": "picture",
    "window": "window",
    "heater": "heater",
    "mirror": "mirror",
    "pipe": "pipe",
    "scarf": "cloth",
    "ceiling_light": "ceiling light",
    "chair": "chair",
    "table": "table",
    "vent": "vent",
    "bag": "bag",
    "wall_cabinet": "cabinet",
    "range": "stove",
    "ricemaker": "rice cooker",
    "pan": "cooking pan",
    "coffee_machine": "coffee maker",
    "rice_bag": "bag",
    "light": "light",
    "trashbin": "trash bin",
    "kettle": "kettle",
    "refrigerator": "refrigerator",
    "microwave": "microwave",
    "light_switch": "light switch",
    "rice_cooker": "rice cooker",
    "box": "box",
    "shoe": "shoe",
    "range_hood": "range hood",
    "wok": "cooking pan",
    "router": "object",
    "paper_towel": "paper towel roll",
    "stock_pot": "pot",
    "cutting_board": "cutting board",
    "wall_calendar": "calendar",
    "baseboard": "object",
    "coke_box": "box",
    "printer": "printer",
    "bowl": "bowl",
    "backpack": "backpack",
    "baseboard_heater": "heater",
    "broom": "broom",
    "dust_pan": "dustpan",
    "trash_bin": "trash bin",
    "rigid_duct": "vent",
    "electric_range": "stove",
    "spatula": "object",
    "faucet": "faucet",
    "bottle": "bottle",
    "countertop": "counter",
    "railing": "railing",
    "suitcase": "suitcase",
    "trash": "trash can",
    "pot": "pot",
    "kitchen_tool": "object",
    "vegetable": "object",
    "board": "board",
    "washing_machine": "washing machine",
    "jar": "jar",
    "object": "object",
    "notebook": "book",
    "induction_cooker": "stove",
    "instant_pot_lid": "cooking pot",
    "oven": "oven",
    "air_fryer": "object",
    "lid": "pot",
    "sponge": "sponge",
    "blender": "object",
    "spoon": "object",
    "dishwasher": "dishwasher",
    "detergent": "laundry detergent",
    "watermelon": "bananas",
    "yard_waste_bag": "garbage bag",
    "container": "container",
    "newspapers": "paper",
    "rag": "cloth",
    "ladder": "ladder",
    "gate": "door",
    "napkin_box": "tissue box",
    "jacket": "jacket",
    "windowsill": "windowsill",
    "water_faucet": "faucet",
    "steel_ball": "ball",
    "rice_maker": "rice cooker",
    "watter_bottle": "water bottle",
    "plastic_bag": "bag",
    "paper_bag": "paper bag",
    "cuttting_board": "cutting board",
    "trash_bin_lid": "trash bin",
    "hair_dryer": "hair dryer",
    "electric_socket": "power outlet",
    "electric_panel": "electric panel",
    "wash_stand": "sink",
    "soap": "soap",
    "curtain": "curtain",
    "bathtub": "bathtub",
    "smoke_detector": "smoke detector",
    "roll_paper": "paper towel roll",
    "chandelier": "chandelier",
    "hand_sanitizer": "hand sanitzer dispenser",
    "plate": "plate",
    "sticker": "sticker",
    "power_socket": "power outlet",
    "stacked_cups": "stack of cups",
    "stacked_chairs": "stack of chairs",
    "air_vent": "vent",
    "cornice": "cabinet",
    "wine_cabinet": "kitchen cabinet",
    "crock": "bowl",
    "liquor_box": "cabinet",
    "shampoo": "shampoo",
    "shower_curtain": "shower curtain",
    "wall_light": "wall lamp",
    "sink_cabinet": "sink",
    "toilet_roll": "toilet paper",
    "shelf": "shelf",
    "paper_bin": "recycling bin",
    "toilet_brush": "toilet brush",
    "shower_head": "shower head",
    "tv": "tv",
    "remote_control": "remote",
    "tv_box": "tv stand",
    "nightstand": "nightstand",
    "bed": "bed",
    "quilt": "blanket",
    "telephone": "telephone",
    "monitor": "monitor",
    "desk": "desk",
    "radiator_shell": "radiator",
    "calendar": "calendar",
    "clock": "clock",
    "keyboard": "keyboard",
    "speaker": "speaker",
    "clothes": "clothes",
    "door_frame": "doorframe",
    "sliding_door": "sliding door",
    "ceiling_lamp": "ceiling lamp",
    "scale": "scale",
    "power_strip": "power strip",
    "switch": "light switch",
    "basket": "basket",
    "stool": "stool",
    "shoes": "shoe",
    "slipper": "slippers",
    "bifold_door": "door",
    "rangehood": "range hood",
    "books": "books",
    "toilet_paper": "toilet paper",
    "mouse_pad": "mouse",
    "ipad": "ipad",
    "scissor": "knife block",
    "radiator": "radiator",
    "pc": "computer tower",
    "bicycle": "bicycle",
    "wardrobe": "wardrobe",
    "mouse": "mouse",
    "advertising_board": "poster",
    "banner": "banner",
    "ceiling_decoration": "ceiling light",
    "whiteboard": "whiteboard",
    "wall_storage_set": "shelf",
    "traffic_cone": "traffic cone",
    "wall_decoration": "decoration",
    "papers": "papers",
    "hat": "hat",
    "velvet_hangers": "clothes hanger",
    "circular_plate": "plate",
    "cellphone": "telephone",
    "pen": "keyboard piano",
    "paper": "paper",
    "lamp": "lamp",
    "curtain_box": "curtains",
    "woodcarving": "wood",
    "scissors": "knife block",
    "hand_dryer": "hand dryer",
    "machine": "machine",
    "vase": "vase",
    "plant": "plant",
    "power_socket_case": "power outlet",
    "gloves": "clothes",
    "dishcloth": "cloth",
    "painting": "painting",
    "shower_wall": "shower wall",
    "showerhead": "shower head",
    "tooth_mug": "cup",
    "map": "map",
    "knot_artwork": "decoration",
    "fan": "fan",
    "sphygmomanometer": "scale",
    "electric_kettle": "kettle",
    "bread_maker": "oven",
    "knife_set": "knife block",
    "soup_pot": "cooking pot",
    "flatware_set": "cutting board",
    "candle": "candle",
    "lid_rack": "dish rack",
    "flower": "flowerpot",
    "can": "can",
    "scoop": "bowl",
    "laptop": "laptop",
    "glass": "glass doors",
    "wet_floor_sign": "wet floor sign",
    "shower_enclosure": "shower doors",
    "jewelry_box": "jewelry box",
    "bath_brush": "hair brush",
    "sofa_cushion": "couch cushions",
    "tv_cabinet": "tv stand",
    "wood_fence": "wood beam",
    "floor_lamp": "lamp",
    "computer_case": "computer tower",
    "waste_container": "trash bin",
    "roadblock": "barricade",
    "trash_can_lids": "trash can",
    "hand_sanitizer_stand": "soap dispenser",
    "air_conditioner": "conditioner bottle",
    "pattern": "rug",
    "remote_controller": "remote",
    "phone": "telephone",
    "speakers": "speaker",
    "table_divider": "divider",
    "table_card": "card",
    "paper_trimmer": "paper cutter",
    "stapler": "stapler",
    "cup": "cup",
    "bathroom_heater": "heater",
    "wall_shelf": "shelf",
    "towel_rack": "towel",
    "sink_drain": "sink",
    "floor_drain": "floor",
    "broom_head": "broom",
    "door_curtain": "curtain",
    "refill_pouch": "plastic container",
    "bin": "bin",
    "stall_wall": "bathroom stall door",
    "wall_speaker": "speaker",
    "laundry_basket": "laundry basket",
    "tissue_box": "tissue box",
    "document_holder": "file cabinet",
    "yoga_mat": "yoga mat",
    "gas_range": "stove",
    "chopping_board": "cutting board",
    "book_scanner": "scanner",
    "payment_terminal": "vending machine",
    "napkin_roll": "paper towel roll",
    "faucet_switch": "faucet",
    "glass_door": "glass doors",
    "carpet": "carpet",
    "shower_floor": "shower floor",
    "toilet_plunger": "plunger",
    "plug_panel": "power outlet",
    "stand": "stand",
    "potted_plant": "potted plant",
    "poster": "poster",
    "isolation_board": "divider",
    "soap_holder": "soap dish",
    "plug": "power outlet",
    "brush": "hair brush",
    "threshold": "doorframe",
    "air_conditioner_controller": "remote",
    "iron": "iron",
    "ironing_board": "ironing board",
    "safe": "suitcase",
    "gas_cooker": "stove",
    "pressure_cooker": "cooking pot",
    "steamer_pot": "pot",
    "soy_sauce_bottle": "bottle",
    "dishwashing_liquid": "dishwashing soap bottle",
    "water_ladle": "bowl",
    "power_socket_set": "power strip",
    "kitchen_tool_holder": "kitchen cabinet",
    "case": "case",
    "wall_paper": "wall",
    "comb": "hair brush",
    "paper_cutter": "paper cutter",
    "pencil_sharpener": "pen holder",
    "sealing_machine": "machine",
    "poster_board": "poster",
    "shredder": "shredder",
    "footstep": "stair",
    "planter": "plant",
    "floor_light": "lamp",
    "paper_cup": "cup",
    "divider": "divider",
    "hanger": "clothes hanger",
    "glove": "clothing",
    "blanket": "blanket",
    "remote": "remote",
    "cloth": "cloth",
    "clutter": "object",
    "extinguisher": "fire extinguisher",
    "dryer": "clothes dryer",
    "soap_bottle": "soap bottle",
    "fabric_softener_box": "box",
    "dryer_sheet_box": "box",
    "detergent_bottle": "laundry detergent",
    "toaster": "toaster",
    "stacked_bowls": "bowl",
    "pot_lid": "pot",
    "electric_pressure_cooker": "rice cooker",
    "bread": "food display",
    "bagels": "object",
    "oranges": "bananas",
    "card_reader": "card",
    "whiteboard_detergent": "soap dispenser",
    "power_outlet": "power outlet",
    "bouquet": "vase",
    "water_bottle": "water bottle",
    "wall_mounted_telephone": "telephone",
    "fridge": "refrigerator",
    "toy": "toy dinosaur",
    "shoe_box": "box",
    "hole_puncher": "paper cutter",
    "landline_telephone": "telephone",
    "base": "stand",
    "handkerchief": "cloth",
    "cornice_molding": "frame",
    "bathtub_base": "bathtub",
    "bidet": "toilet",
    "pedestal_urinal": "urinal",
    "pedestal_urinal_covered": "urinal",
    "pit_toilet": "toilet",
    "low_wall": "wall",
    "rail": "rail",
    "bottles": "bottles",
    "floor_otherroom": "floor",
    "wall_otherroom": "wall",
    "canopy": "canopy",
    "cable_manager": "cable",
    "sneakers": "shoes",
    "purse": "purse",
    "cushion": "cushion",
    "napkin": "towel",
    "plush_toy": "stuffed animal",
    "adjustable_desk": "desk",
    "tableware": "plates",
    "computer_desk": "desk",
    "cat_kennel": "cat litter box",
    "back_cushion": "pillow",
    "ukulele_bag": "guitar case",
    "litter_box": "trash can",
    "storage_box": "storage bin",
    "toy_doll": "doll",
    "drawer_unit": "drawer",
    "doll": "stuffed animal",
    "laptop_bag": "messenger bag",
    "clothing_rack": "clothing rack",
    "bookshelf": "bookshelves",
    "mask": "cloth",
    "watch": "clock",
    "book": "books",
    "ashtray": "tray",
    "car_key": "car",
    "wallet": "purse",
    "tea_pot": "tea kettle",
    "wire": "cable",
    "rake": "broom",
    "dispenser": "soap dispenser",
    "toilet_tank": "toilet",
    "door_sill": "doorframe",
    "cleanser": "soap",
    "armrest": "armchair",
    "short_wall": "wall",
    "suspended_ceiling": "ceiling",
    "fire_extinguisher_cabinet": "fire extinguisher",
    "plastic_box": "plastic container",
    "sanitation_station": "soap dispenser",
    "plant_pot": "flowerpot",
    "fireplace": "fireplace",
    "computer_table": "desk",
    "tissue_bag": "tissue box",
    "wall_frame": "frame",
    "map_board": "map",
    "automated_teller_machine": "vending machine",
    "ticket": "card",
    "tablet": "ipad",
    "blankets": "blanket",
    "bags": "bag",
    "flag": "flag",
    "blackboard": "blackboard",
    "bar_table": "bar",
    "cardboard_holder": "cardboard",
    "potted_planet": "potted plant",
    "tray": "tray",
    "utensil_holder": "kitchen counter",
    "bird_ceramics": "statue",
    "shirt": "shirt",
    "clothes_rail": "clothes hanger",
    "power_strips": "power strip",
    "card_board": "board",
    "pile_of_blankets": "blanket",
    "bed_net": "bed",
    "umbrella": "umbrella",
    "dragon_fruit": "bananas",
    "tissue": "tissue box",
    "electrical_panel": "electric panel",
    "panel": "door",
    "tube": "tube",
    "pile_of_cloth": "cloth",
    "surface": "table",
    "chair_cushion": "cushion",
    "guide": "book",
    "parapet": "railing",
    "camera": "camera",
    "light_base": "lamp base",
    "first_aid": "object",
    "bench": "bench",
    "potted_plants": "potted plant",
    "pot_cover": "pot",
    "yoga_mat_roll": "yoga mat",
    "panda_doll": "stuffed animal",
    "window_trim": "window",
    "shoe_cabinet": "shoe rack",
    "toilet_paper_holder": "toilet paper dispenser",
    "shower_faucet": "shower faucet handle",
    "bath_sponge": "sponge",
    "ornament": "decoration",
    "planter_box": "plant",
    "cooktop": "stove",
    "knife_block": "knife block",
    "step_stool": "step stool",
    "touchpad": "keyboard",
    "light_box": "light",
    "sound": "speaker",
    "exhaust_fan_vent": "vent",
    "paperbin": "recycling bin",
    "mop_bucket": "bucket",
    "sneaker": "shoes",
    "objects": "object",
    "cd_tray": "cd case",
    "wall_board": "board",
    "room_divider": "divider",
    "paiting": "painting",
    "cabinet_otherroom": "cabinet",
    "electric_switch": "light switch",
    "sign": "exit sign",
    "hand_soap": "soap bottle",
    "window_blinds": "blinds"
}


RSCAN_SCANNET = {
'pillow': 'pillow',
'box': 'box',
'item': 'object',
'curtain': 'curtain',
'towel': 'towel',
'garbage bin': 'trash bin',
'wall': 'wall',
'floor': 'floor',
'figure': 'statue',
'frame': 'frame',
'shelf': 'shelf',
'clothes': 'clothing',
'picture': 'picture',
'organizer': 'organizer shelf',
'ceiling': 'ceiling',
'object': 'object',
'cabinet': 'cabinet',
'blanket': 'blanket',
'monitor': 'monitor',
'door': 'door',
'roll': 'paper towel roll',
'bed': 'bed',
'desk': 'desk',
'window': 'window',
'nightstand': 'nightstand',
'rack': 'rack stand',
'plant': 'potted plant',
'cushion': 'cushion',
'light': 'light',
'table': 'table',
'windowsill': 'windowsill',
'shades': 'blinds',
'sofa': 'sofa',
'beanbag': 'beanbag chair',
'commode': 'toilet',
'heater': 'heater',
'trash can': 'trash can',
'child chair': 'stool',
'mirror': 'mirror',
'lamp': 'lamp',
'sink': 'sink',
'cupboard': 'kitchen cabinet',
'toilet paper': 'toilet paper rolls',
'toilet': 'toilet',
'handhold': 'hand rail',
'vase': 'vase',
'toilet brush': 'toilet brush',
'armchair': 'armchair',
'doorframe': 'doorframe',
'bathtub': 'bathtub',
'bath cabinet': 'bathroom cabinet',
'basket': 'basket',
'shower curtain': 'shower curtain',
'bin': 'trash bin',
'kitchen hood': 'range hood',
'kitchen cabinet': 'kitchen cabinet',
'kitchen sofa': 'sofa',
'chair': 'chair',
'rag': 'towel',
'kitchen counter': 'kitchen counter',
'oven': 'oven',
'microwave': 'microwave',
'fruit plate': 'plate',
'player': 'keyboard piano',
'kitchen appliance': 'microwave',
'kettle': 'kettle',
'wardrobe': 'wardrobe closet',
'stool': 'stool',
'stand': 'stand',
'shoes': 'shoes',
'counter': 'counter',
'hand dryer': 'hand dryer',
'suitcase': 'suitcase',
'closet': 'closet',
'tv': 'tv',
'bag': 'bag',
'laptop': 'laptop',
'jalousie': 'blinds',
'whiteboard': 'whiteboard',
'planter': 'flowerpot',
'shower': 'shower',
'hanging cabinet': 'kitchen cabinets',
'flower': 'plant',
'washbasin': 'sink',
'clothes dryer': 'clothes dryers',
'sack': 'bag',
'basin': 'sink',
'radiator': 'radiator',
'refrigerator': 'refrigerator',
'clutter': 'object',
'vacuum cleaner': 'vacuum cleaner',
'shelf unit': 'shelf',
'mop': 'broom',
'ironing board': 'ironing board',
'iron': 'iron',
'bucket': 'bucket',
'toy': 'doll',
'stairs': 'stairs',
'barrel': 'container',
'washing machine': 'washing machine',
'carpet': 'carpet',
'sidecouch': 'couch',
'tv stand': 'tv stand',
'bench': 'bench',
'humidifier': 'humidifier',
'hanger': 'clothes hanger',
'backpack': 'backpack',
'drawer': 'drawer',
'console': 'computer tower',
'hangers': 'clothes hanger',
'blinds': 'blinds',
'balcony door': 'door',
'upholstered wall': 'wall',
'coffee table': 'coffee table',
'blackboard': 'blackboard',
'glass wall': 'window',
'bottles': 'bottle',
'pack': 'bag',
'scale': 'scale',
'ventilation': 'fan',
'paper towel': 'paper towel roll',
'bottle': 'bottle',
'dish dryer': 'dish rack',
'candle': 'candle',
'pc': 'computer tower',
'washing': 'washing machine',
'tube': 'tube',
'snowboard': 'board',
'board': 'board',
'pipe': 'pipe',
'water heater': 'water heater',
'vacuum': 'vacuum cleaner',
'stuffed animal': 'stuffed animal',
'decoration': 'decoration',
'shower wall': 'shower wall',
'telephone': 'telephone',
'plate': 'plate',
'watering can': 'can',
'device': 'object',
'stove': 'stove',
'kitchen towel': 'towel',
'garbage': 'trash can',
'shampoo': 'shampoo bottle',
'statue': 'statue',
'shower door': 'shower door',
'book': 'book',
'fan': 'fan',
'speaker': 'speaker',
'pile of books': 'books',
'side table': 'end table',
'table lamp': 'table lamp',
'couch': 'couch',
'magazine': 'magazine',
'papers': 'papers',
'books': 'books',
'furniture': 'furniture',
'magazine files': 'magazine rack',
'mannequin': 'object',
'boxes': 'boxes',
'clock': 'clock',
'cube': 'object',
'napkins': 'cloth',
'stuffed': 'stuffed animal',
'luggage': 'luggage',
'partition': 'divider',
'trash': 'trash can',
'coffee': 'coffee maker',
'bar': 'bar',
'newspaper': 'paper',
'wood': 'wood',
'fireplace': 'fireplace',
'dining': 'dining table',
'dining table': 'dining table',
'bread': 'object',
'fruits': 'object',
'kitchen': 'kitchen cabinet',
'can': 'can',
'squeezer': 'object',
'bowl': 'bowl',
'recycle': 'recycling bin',
'barstool': 'stool',
'computer': 'computer tower',
'umbrella': 'umbrella',
'bath': 'bathtub',
'hanging': 'hanging',
'rocking': 'object',
'objects': 'object',
'flowers': 'plant',
'plants': 'plant',
'jar': 'jar',
'bedside': 'nightstand',
'buggy': 'object',
'side': 'object',
'socket': 'power outlet',
'showcase': 'display case',
'drying': 'drying rack',
'ottoman': 'ottoman',
'pictures': 'pictures',
'storage': 'storage bin',
'footstool': 'footstool',
'folding': 'folded chair',
'ladder': 'ladder',
'shoe': 'shoes',
'pet': 'object',
'medical': 'object',
'soap': 'soap',
'balcony': 'object',
'foosball': 'foosball table',
'hand': 'object',
'bookshelf': 'bookshelf',
'pile': 'object',
'cleaning': 'object',
'flush': 'toilet flush button',
'towels': 'towels',
'candlestick': 'candle',
'puf': 'object',
'printer': 'printer',
'shelves': 'shelf',
'stair': 'stair',
'cleanser': 'soap bottle',
'armoire': 'wardrobe closet',
'bidet': 'object',
'exit': 'exit sign',
'toaster': 'toaster',
'laundry': 'laundry basket',
'hood': 'range hood',
'sponge': 'sponge',
'fridge': 'refrigerator',
'breadboard': 'cutting board',
'pan': 'frying pan',
'water': 'water bottle',
'teapot': 'tea kettle',
'projector': 'projector',
'juicer': 'kitchen mixer',
'cutting': 'cutting board',
'windows': 'windowsill',
'food': 'food container',
'cup': 'cup',
'rug': 'rug',
'column': 'column',
'keyboard': 'keyboard',
'office': 'office chair',
'exhaust': 'range hood',
'apron': 'kitchen apron',
'pepper': 'salt',
'knife': 'knife block',
'cooking': 'cooking pot',
'tablet': 'ipad',
'bicycle': 'bicycle',
'pillar': 'pillar',
'machine': 'washing machine',
'meter': 'scale',
'cut': 'paper cutter',
'salt': 'salt',
'candles': 'candle',
'grass': 'plant',
'sidetable': 'end table',
'sewing': 'sewing machine',
'guitar': 'guitar',
'flag': 'flag',
'paper': 'paper',
'sugar': 'bowl',
'cups': 'cups',
'packs': 'boxes',
'plates': 'plates',
'tray': 'tray',
'chandelier': 'chandelier',
'mandarins': 'bananas',
'puppet': 'doll',
'painting': 'painting',
'cradle': 'crib',
'price': 'tag',
'dish': 'dish rack',
'boiler': 'boiler',
'fruit': 'bananas',
'multicooker': 'rice cooker',
'items': 'object',
'extractor': 'juicer',
'air': 'fan',
'dressing': 'mirror',
'round': 'round table',
'screen': 'screen',
'mattress': 'mattress',
'bike': 'bicycle',
'rolled': 'rolled poster',
'locker': 'cabinet',
'tennis': 'tennis racket',
'cap': 'cap',
'ball': 'ball',
'folder': 'folder',
'milk': 'refridgerator',
'dishdrainer': 'dish rack',
'dishwasher': 'dishwasher',
'piano': 'piano',
'stereo': 'speaker',
'upholstered': 'couch',
'folded': 'folded chairs',
'loft': 'loft bed',
'aquarium': 'fish',
'dispenser': 'soap dispenser',
'body': 'person',
'sign': 'sign',
'baby': 'crib',
'chest': 'chest',
'pot': 'pot',
'drawers': 'drawer',
'rail': 'rail',
'platform': 'platform',
'tree': 'plant',
'armor': 'helmet',
'ironing': 'ironing board',
'headboard': 'headboard',
'crib': 'crib',
'beverage': 'bottle',
'plank': 'wood',
'generator': 'machine',
'file': 'file cabinet',
'coat': 'coat rack',
'tool': 'toolbox',
'rolling': 'cart',
'tire': 'tire',
'cable': 'cable',
'fence': 'gate',
'handrail': 'handrail',
't-shirt': 'shirt',
'ramp': 'stairs',
'seat': 'seat',
'sideboard': 'cabinet',
'lounger': 'chair',
'discs': 'cd case',
'drum': 'drum set',
'drinks': 'soda can',
'chairs': 'chair',
'dishes': 'dish rack',
'linen': 'towel',
'glass': 'glass',
'xbox': 'xbox controller',
'ukulele': 'guitar',
'pin': 'needle'
}


HM3D_SCANNET = {
"wall": "wall",
"picture": "picture",
"floor": "floor",
"fireplace": "fireplace",
"window": "window",
"window frame": "window",
"door": "door",
"door knob": "door",
"door frame": "doorframe",
"ceiling": "ceiling",
"ceiling fan": "ceiling fan",
"fireplace shelf": "fireplace",
"hearth": "fireplace",
"fireplace floor": "fireplace",
"armchair": "armchair",
"table": "table",
"coffee table": "coffee table",
"table lamp": "table lamp",
"sofa": "sofa",
"pillow": "pillow",
"tv stand": "tv stand",
"tv": "tv",
"device": "object",
"chair": "chair",
"cutlery": "knife block",
"plate": "plate",
"napkins": "towel",
"ceiling lamp": "ceiling light",
"kitchen cabinet": "kitchen cabinet",
"shelf": "shelf",
"fridge": "refrigerator",
"microwave": "microwave",
"kitchen cabinet lower": "kitchen cabinet",
"coffee machine": "coffee maker",
"oven": "oven",
"kettle": "kettle",
"tray": "tray",
"knife set": "kitchen cabinet",
"wall lamp": "wall lamp",
"sink": "sink",
"tap": "faucet",
"detergent": "soap",
"unknown": "object",
"toaster": "toaster",
"dishwasher": "dishwasher",
"cabinet": "cabinet",
"bed": "bed",
"bedside table": "nightstand",
"clock": "clock",
"air vent": "vent",
"hanger": "clothes hanger",
"mirror": "mirror",
"wash cabinet": "bathroom vanity",
"washbasin": "sink",
"faucet": "faucet",
"cosmetic": "toiletry",
"soap": "soap",
"cosmetics": "toiletry",
"towel": "towel",
"bin": "bin",
"toilet paper": "toilet paper",
"toilet": "toilet",
"bath": "bathtub",
"bath curtain": "shower curtain",
"curtain bar": "curtain rod",
"bath shelf": "shelf",
"bath dial": "shower faucet handle",
"bath faucet": "faucet",
"decoration": "decoration",
"tissue box": "tissue box",
"hand towel": "hand towel",
"storage unit": "storage bin",
"shower wall": "shower wall",
"shower seat": "seat",
"shower floor": "shower floor",
"shower cabin": "shower",
"shower curtain": "shower curtain",
"shower bar": "handrail",
"showerhead": "shower head",
"shower dial": "shower faucet handle",
"shower hanger": "clothes hanger",
"rug": "rug",
"fire detector": "smoke detector",
"banister": "banister",
"plunger": "plunger",
"rod": "rod",
"washer-dryer": "washing machine",
"couch": "couch",
"lamp": "lamp",
"pouffe": "ottoman",
"furniture": "furniture",
"fan": "fan",
"chest of drawers": "dresser",
"curtain": "curtain",
"curtain rod": "curtain rod",
"desk": "desk",
"hanging clothes": "clothing",
"barrel": "container",
"bathtub": "bathtub",
"drawer": "drawer",
"countertop": "counter",
"bathroom shelf": "shelf",
"knob": "door",
"toilet brush": "toilet",
"shower knob": "shower",
"stairs": "staircase",
"handrail": "banister",
"bathroom cabinet": "bathroom vanity",
"paper towel": "paper towel dispenser",
"towel ring": "towel",
"towel bar": "towel",
"kitchen counter": "kitchen cabinet",
"refrigerator": "mini fridge",
"vase": "flowerpot",
"kitchen utensil": "cooking pot",
"kitchen countertop item": "kitchen counter",
"shelving": "shelf",
"pitcher": "water pitcher",
"bowl": "bowl",
"kitchen island": "kitchen counter",
"trashcan": "trash can",
"stove": "oven",
"box": "storage box",
"clutter": "object",
"painting": "picture",
"book": "bookshelf",
"toy": "stuffed animal",
"heater": "radiator",
"ceiling vent": "vent",
"floor mat": "mat",
"hand soap": "soap dispenser",
"flower": "potted plant",
"toilet paper dispenser": "toilet paper",
"bathrobe": "bathrobe",
"bed table": "nightstand",
"bedside lamp": "lamp",
"folding chair": "folded chair",
"patio chair": "chair",
"grill": "oven",
"balustrade": "banister",
"attic door": "door",
"sensor": "smoke detector",
"wall hanging decoration": "decoration",
"doormat": "mat",
"clothes hanger": "clothes",
"wall cabinet": "cabinet",
"wall clock": "clock",
"led tv": "tv",
"fireplace wall": "fireplace",
"firewood holder": "wood",
"floor lamp": "lamp",
"curtain rail": "curtain rod",
"wine rack": "bar",
"wine bottle": "bottle",
"wall electronics": "power outlet",
"washing machine": "washing machines",
"kitchen appliance": "kitchen cabinets",
"bed light": "lamp",
"electric box": "electric panel",
"guitar": "guitar case",
"media console": "tv stand",
"newspaper": "magazine",
"wardrobe": "wardrobe closet",
"bottle of soap": "soap bottle",
"ventilation hood": "range hood",
"sauna heater": "heater",
"sauna bowl": "bowl",
"rail": "handrail",
"spa bench": "bench",
"bathroom utensil": "toiletry",
"recessed wall": "wall",
"art frame": "picture",
"appliance": "machine",
"decorative plant": "potted plant",
"flowerpot": "vase",
"door/window frame": "doorframe",
"cardboard box": "box",
"shoe": "shoes",
"clothes": "clothing",
"clothes rack": "clothing rack",
"shelf with clutter": "shelf",
"case": "suitcase",
"backpack": "messenger bag",
"hat": "cap",
"storage cabinet": "cabinet",
"bag": "grocery bag",
"basket of something": "basket",
"blanket": "blanket",
"vacuum cleaner": "roomba",
"window shutter": "blinds",
"exercise bike": "exercise machine",
"door/window": "doorframe",
"plant": "potted plant",
"bath sink": "sink",
"shower hose": "shower head",
"ironing board": "iron",
"stand": "podium",
"rack": "rack stand",
"bottle of detergent": "laundry detergent",
"storage box": "storage container",
"jar": "container",
"ceiling dome": "ceiling",
"container": "box",
"refrigerator cabinet": "refrigerator",
"compound wall": "wall",
"glass": "cup",
"bottle": "bottle",
"speaker": "speaker",
"telephone": "telephone",
"sofa chair": "sofa chair",
"small table/stand": "end table",
"blinds": "blinds",
"stairs railing": "stair rail",
"bar": "bar",
"air conditioner": "vent",
"bed stand": "nightstand",
"shower door frame": "shower door",
"bathroom accessory": "soap dispenser",
"trash can": "trash can",
"liquid soap": "soap",
"desk chair": "office chair",
"desk clutter": "papers",
"book rack": "bookshelf",
"wall panel": "wall",
"closet area for hanging clothes": "wardrobe closet",
"laundry basket": "laundry basket",
"shower rod": "shower curtain rod",
"shower hose/head": "shower head",
"box of tissues": "tissue box",
"shower ceiling": "ceiling",
"plush toy": "stuffed animal",
"dresser": "dresser",
"recycle bin": "recycling bin",
"desk lamp": "desk lamp",
"basket": "basket",
"drum": "instrument case",
"stack of papers": "papers",
"bath towel": "towel",
"bath cabinet": "bathroom cabinet",
"carpet": "carpet",
"printer": "printer",
"bench": "bench",
"flower vase": "vase",
"furnace": "heater",
"sink cabinet": "bathroom vanity",
"paper": "paper",
"bath wall": "bath walls",
"shower soap shelf": "soap dish",
"chandelier": "chandelier",
"window curtain": "curtain",
"monitor": "monitor",
"keyboard": "keyboard",
"computer mouse": "mouse",
"computer desk": "desk",
"board": "board",
"snack": "food container",
"machine": "machine",
"mini fridge": "mini fridge",
"arcade game": "machine",
"exercise machine": "exercise machine",
"shutter": "door",
"pad": "pillow",
"computer equipment": "computer tower",
"computer chair": "office chair",
"wall shelf": "shelf",
"staircase handrail": "handrail",
"bed small": "bed",
"dog bed": "pillow",
"photo": "picture",
"lamp table": "table lamp",
"footstool": "footstool",
"bath utensil": "bath products",
"brush": "hair brush",
"chest": "chest",
"throw blanket": "blanket",
"bowl of fruit": "bowl",
"highchair": "seat",
"laptop": "laptop",
"file cabinet": "file cabinet",
"food stand": "food display",
"dining table": "dining table",
"wall toilet paper": "toilet paper holder",
"cabinet table": "cabinet",
"ventilation": "vent",
"wall indent": "wall",
"window glass": "window",
"bath tub": "bathtub",
"cabinet door": "cabinet door",
"support beam": "wood beam",
"holder": "soap dish",
"side table": "end table",
"smoke detector": "smoke detector",
"dinnerware": "plates",
"dinner table": "dining table",
"mirror /otherroom": "mirror",
"shower": "shower",
"pipe": "pipe",
"motion detector": "alarm",
"paper towel holder": "paper towel dispenser",
"ornament": "decoration",
"bedside cabinet": "nightstand",
"ceiling door": "door",
"stool": "stool",
"countertop item": "kitchen counter",
"island": "kitchen island",
"range hood": "range hood",
"door cabinet": "cabinet door",
"window /outside": "window",
"frame": "frame",
"rocking chair": "chair",
"fruit": "banana holder",
"tissue": "tissue box",
"plate of food": "plate",
"shower curtain rod": "shower curtain rod",
"shower tap": "shower faucet handle",
"soapbox": "soap bar",
"soap dispenser": "soap dispenser",
"remote control": "remote",
"ceiling duct": "vent",
"pool stick": "pool table",
"statue": "statue",
"mat": "mat",
"fire alarm": "fire alarm",
"toilet brush holder": "toilet brush",
"vent": "vent",
"step": "step",
"shower pipe": "shower head",
"laundry machine": "washing machine",
"bucket": "bucket",
"broom": "broom",
"cutting board": "cutting board",
"oven and stove": "oven",
"oven vent": "vent",
"kitchen countertop items": "kitchen counter",
"kitchen lower cabinet": "kitchen cabinet",
"grate": "vent",
"beam": "wood beam",
"pillar": "pillar",
"dining chair": "chair",
"basket of towels": "towels",
"stair handle": "handrail",
"stair": "stair",
"stair wall": "wall",
"exercise ball": "exercise ball",
"exercise equipment": "exercise machine",
"exercise mat": "yoga mat",
"bedframe": "bedframe",
"lamp stand": "lamp base",
"pool table": "pool table",
"dartboard": "dart board",
"bar cabinet": "bar",
"bar chair": "chair",
"display cabinet": "display case",
"display table": "table",
"screen": "screen",
"teapot": "tea kettle",
"railing": "railing",
"unknown/remove": "object",
"alarm clock": "alarm clock",
"alarm": "alarm",
"hunting trophy": "decoration",
"water dispenser": "water cooler",
"antique telephone": "telephone",
"calendar": "calendar",
"knife holder": "rack",
"spice rack": "rack",
"fireplace tool set": "fireplace",
"firewood": "wood",
"ceiling under staircase": "ceiling",
"can": "can",
"bathtub platform": "bathtub",
"scale": "scale",
"tile": "floor",
"belt": "clothing",
"parapet": "railing",
"three": "object",
"computer": "computer tower",
"treadmill": "treadmill",
"duct": "vent",
"electrical box": "electric panel",
"stair frame": "stair",
"ladder": "ladder",
"water heater": "water heater",
"heater piping": "pipe",
"exhaust pipe": "pipe",
"pump": "water cooler",
"hose": "hose",
"switch": "light switch",
"storage bin": "storage bin",
"plastic bag": "bag",
"wall board": "board",
"washing machine and dryer": "washing machine",
"flag": "flag",
"can of paint": "can",
"broomstick": "broom",
"plumbing": "pipe",
"column": "column",
"ceiling pipe": "pipe",
"cables": "power strip",
"landing": "stairs",
"ledge": "ledge",
"mop": "broom",
"tv remote": "remote",
"closet door": "closet door",
"door window": "door",
"door hinge": "door",
"doorway": "doorframe",
"alarm control": "alarm",
"radiator": "radiator",
"ceiling light fixture connection": "ceiling light",
"mirror frame": "mirror",
"mantel": "fireplace",
"firebox": "fireplace",
"fireplace sconce": "fireplace",
"fume cupboard": "cabinet",
"decorative bowl": "bowl",
"stonework": "wall",
"kitchen shelf": "kitchen cabinet",
"window shade": "curtain",
"radio": "speaker",
"cooker": "stove",
"kitchen table": "dining table",
"cup": "cup",
"tiles": "floor",
"washbasin counter": "sink",
"doorstep": "door",
"stairs wall": "stairs",
"stairs trim": "stairs",
"stacked chair": "stack of chairs",
"carpet roll": "carpet",
"safe": "cabinet",
"briefcase": "briefcase",
"door stopper": "door",
"shades": "blinds",
"electric cable": "power strip",
"nightstand": "nightstand",
"clothes hanger rod": "closet rod",
"shower stall": "shower",
"sink/basin": "sink",
"worktop": "kitchen counter",
"basin": "sink",
"diploma": "frame",
"garage door": "garage door",
"garage door frame": "garage door",
"garage door opener": "garage door",
"boxes": "boxes",
"jacket": "jacket",
"tree": "plant",
"tree branch": "plant",
"shovel": "broom",
"tool": "toolbox",
"binder": "binders",
"paper storage": "paper tray",
"folder": "file cabinet",
"flower stand": "plant",
"coat hanger": "clothes hanger",
"wall detail": "wall",
"boiler": "boiler",
"shower-bath cabinet": "bathroom cabinet",
"sofa seat": "sofa",
"platform": "platform",
"panel": "wall",
"coffee maker": "coffee maker",
"dish cabinet": "dish rack",
"candle holder": "candle",
"ceiling molding": "ceiling",
"bed comforter": "bed",
"cuddly toy": "teddy bear",
"decorative plate": "plate",
"figure": "statue",
"bouquet": "flowerpot",
"kitchen extractor": "range hood",
"pot": "pot",
"vessel": "bowl",
"kitchen top": "kitchen counter",
"painting frame": "painting",
"casket": "chest",
"bathroom towel": "towel",
"washing stuff": "soap",
"shelf cubby": "shelf",
"shower rail": "shower curtain rod",
"cloth": "cloth",
"stick": "rod",
"luggage": "luggage",
"sconce": "wall lamp",
"lounge chair": "armchair",
"patio floor": "floor",
"roof": "ceiling",
"jewelry": "jewelry box",
"bedroom ceiling": "ceiling",
"cushion": "pillow",
"ceiling bedroom": "ceiling",
"record player": "speaker",
"perfume": "soap",
"shower handle": "shower faucet handle",
"shampoo": "shampoo bottle",
"weight": "dumbbell",
"candlestick": "candle",
"cabinet kitchen": "kitchen cabinet",
"antique clock": "clock",
"picture frame": "picture",
"candle": "candle",
"air conditioning": "fan",
"floor /outside": "floor",
"fence": "rail",
"canopy": "canopy",
"end table": "end table",
"shelf with art": "shelf",
"dishrag": "towel",
"staircase trim": "staircase",
"bookshelf": "bookshelf",
"decorative quilt": "blanket",
"shower tub": "bathtub",
"clothes dryer": "clothes dryer",
"clothes hamper": "laundry hamper",
"bathroom counter": "bathroom counter",
"cart": "cart",
"weight bench": "bench",
"rack of weights": "dumbbell",
"ceiling under stairs": "ceiling",
"storage shelving": "storage shelf",
"office chair": "office chair",
"doll": "doll",
"step stool": "step stool",
"pc tower": "computer tower",
"control panel": "electric panel",
"umbrella": "umbrella",
"food": "food container",
"closet": "closet",
"fireplace utensil": "fireplace",
"holy cross": "decoration",
"tablet": "ipad",
"mug": "mug",
"box of tissue": "tissue box",
"sled": "luggage stand",
"electrical controller": "electric panel",
"dressing table": "dresser",
"freezer": "refrigerator",
"paneling": "wall",
"object": "object",
"pile of magazines": "magazine",
"objects": "object",
"counter": "counter",
"outlet": "power outlet",
"fire extinguisher": "fire extinguisher",
"entertainment set": "tv stand",
"window shutters": "blinds",
"window valence": "curtain",
"shower curtain bar": "shower curtain rod",
"statue/art": "statue",
"brochure": "paper",
"trinket": "decoration",
"toilet cleaner": "toilet brush",
"air duct": "vent",
"plank": "wood",
"bed cabinet": "nightstand",
"ottoman": "ottoman",
"air refresher": "spray bottle",
"cleaner": "vacuum cleaner",
"shower shelf": "shower",
"ceiling lower": "ceiling",
"cases": "suitcases",
"magazines": "magazine",
"grab bar": "grab bar",
"bath door frame": "doorframe",
"shower door knob": "shower door",
"document": "paper",
"cleaning paper": "paper towel roll",
"bath floor": "floor",
"shower bench": "bench",
"shower step": "step",
"slippers": "slippers",
"boots": "shoes",
"weights": "dumbbell",
"cap": "cap",
"note": "paper",
"golf sticks": "golf bag",
"glasses": "mirror",
"medal collection": "decoration",
"decorative dinnerware": "plate",
"music player": "speaker",
"jug": "pitcher",
"sliding door": "door",
"kitchen knife set": "kitchen cabinet",
"sitting bench": "bench",
"bowl with sweets": "bowl",
"decorative vase": "vase",
"rolled carpet": "carpet",
"ball": "ball",
"dumbbell": "dumbbell",
"folded chair": "folded chair",
"screen frame": "screen",
"speaker stand": "speaker",
"projector": "projector",
"bath tap": "faucet",
"stuffed animal": "stuffed animal",
"ceiling window": "window",
"kitchen handle": "kitchen cabinet",
"podium": "podium",
"office table": "desk",
"button": "toilet flush button",
"decoder": "computer tower",
"food tray": "tray",
"elevator": "elevator",
"bathtub utensil": "bathtub",
"footrest": "footrest",
"stair step": "stairs",
"ceiling light": "ceiling light",
"telescope": "telescope",
"ping pong table": "ping pong table",
"photo mount": "picture",
"bookstand": "bookshelf",
"curtain rod cover": "curtain rod",
"baby changing table": "changing station",
"bulletin board": "bulletin board",
"stack of jackets": "jacket",
"crib": "crib",
"kitchen cabinet door": "cabinet door",
"kitchen cabinet drawer": "kitchen cabinet",
"potty": "toilet",
"bottles of wine": "beer bottles",
"table cloth": "table",
"iron board": "ironing board",
"shoes": "shoes",
"bottles of water": "water bottle",
"watch": "clock",
"cable": "power outlet",
"desk door": "desk",
"notebook": "book",
"file binder": "binders",
"bathroom stuff": "bath products",
"bath mat": "mat",
"handbag": "bag",
"robe": "bathrobe",
"sculpture": "statue",
"kitchen decoration": "decoration",
"pan": "cooking pan",
"handle": "door",
"bicycle": "bicycle",
"piano": "piano",
"piano stool": "piano bench",
"wall post": "wall",
"magazine": "magazine",
"cover": "cover",
"tool box": "toolbox",
"wood": "wood",
"support": "structure",
"hook": "rack",
"gravel": "floor",
"rafter": "wood beam",
"soap bottle": "soap bottle",
"dustbin": "trash bin",
"light": "light",
"sign": "sign",
"plates": "plate",
"thermostat": "thermostat",
"mascot": "stuffed animal",
"stack of books": "stack of chairs",
"stack of books / papers": "papers",
"decorative cloth": "cloth",
"locker": "cabinet",
"wine storage": "cabinet",
"cleaning liquid": "dishwashing soap bottle",
"cleaning sponge": "sponge",
"stack of pots": "pot",
"seat": "seat",
"air vent fan": "fan",
"shower handrail": "handrail",
"ceiling fire detector": "smoke detector",
"ceiling fan vent": "vent",
"curtain hanger": "curtain rod",
"bath bar": "bath walls",
"book cabinet": "bookshelf",
"desk cabinet": "desk",
"papers": "papers",
"sheets / clothes": "clothes",
"wall hanger": "wall mounted coat rack",
"ceiling lamp hanger": "ceiling lamp",
"stack of stuff": "stack of chairs",
"socket": "power outlet",
"shower door": "shower door",
"fan air vent": "vent",
"crate": "crate",
"wire": "power outlet",
"installation": "structure",
"sideboard": "cabinet",
"wall sign": "sign",
"camera": "camera",
"urinal": "urinal",
"stone support structure": "structure",
"bottles": "bottles",
"bathroom mat": "mat",
"shower ceiling lamp": "ceiling lamp",
"shower cosmetics": "bath products",
"fire sprinkler": "fire extinguisher",
"bowl of sweets": "bowl",
"sprinkler": "hose",
"self-closing mechanism": "door",
"utensil": "kitchen cabinet",
"control": "light switch",
"headphones": "headphones",
"bidet": "toilet",
"arch": "doorframe",
"closet shelving": "closet",
"bean bag chair": "beanbag chair",
"scarf": "clothes",
"shelf clutter": "shelf",
"bed sheet": "bed",
"bowl of fruits": "bowl",
"cabinet clutter": "cabinet",
"light fixture": "ceiling light",
"dvd player": "tv",
"surface": "table",
"surfboard": "board",
"whine shelf": "shelf",
"amplifier": "speaker",
"stereo": "speaker",
"fire screen": "fireplace",
"ice maker": "refrigerator",
"knife": "kitchen cabinet",
"closet mirror wall": "mirror",
"table tennis table": "ping pong table",
"baby changing station": "changing station",
"book display": "bookshelf",
"sliding glass door": "door",
"l-shaped sofa": "sofa",
"soap dish": "soap dish",
"mixer": "kitchen mixer",
"puppet": "doll",
"electric guitar": "guitar",
"music album shelf": "shelf",
"bathroom floor": "floor",
"powder soap": "soap",
"decorative lamp": "lamp",
"toothbrush": "toothbrush",
"shower grab bar": "grab bar",
"candle stand": "candle",
"electric outlet": "power outlet",
"photos": "pictures",
"shower caddy": "shower",
"mouse": "mouse",
"car model": "car",
"guitar frame": "guitar case",
"ship toy": "boat",
"platter": "plate",
"decorative bottle": "bottle",
"audio player": "speaker",
"firewood chest": "chest",
"kitchen seating": "seat",
"hats": "hat",
"cat toilet": "cat litter box",
"electric kettle": "kettle",
"security camera": "camera",
"light switch": "light switch",
"schedule": "calendar",
"globe": "globe",
"magazine rack": "magazine",
"ceiling/west wall": "ceiling",
"shelf with shoes": "shoe rack",
"kitchen lower shelf": "kitchen cabinet",
"sewing machine": "sewing machine",
"sewing set": "sewing machine",
"sewing tools": "sewing machine",
"strings": "rope",
"decorative lantern": "lamp",
"paper towel dispenser": "paper towel dispenser",
"stack of cds": "cd case",
"stationery": "paper",
"shutters": "blinds",
"keys": "cabinet",
"rope": "rope",
"iron": "iron",
"trolley": "trolley",
"closet shelf": "closet",
"ceiling wall": "ceiling",
"coach": "sofa",
"sink table": "sink",
"pool": "pool table",
"entrance arch": "doorframe",
"ceiling arch": "ceiling",
"arcade": "object",
"ceiling support": "pillar",
"map": "map",
"stained glass": "window",
"ceiling decorative lamp": "ceiling light",
"bust": "statue",
"framed text": "picture",
"ceiling boarder": "ceiling",
"exhibition window frame": "window",
"exhibition window": "window",
"elevator door": "elevator",
"exhibition panel": "display case",
"information": "sign",
"chassis": "structure",
"ceiling ladder": "ladder",
"exhibition picture": "picture",
"exhibition table": "table",
"ship model": "boat",
"garage door opener motor": "garage door",
"garage door opener bar": "bar",
"garage door railing": "railing",
"riser": "stairs",
"dustpan": "dustpan",
"coat": "coat",
"doorpost": "doorframe",
"backrest": "chair",
"fruit bowl": "bowl",
"easy chair": "armchair",
"stone": "object",
"ashtray": "container",
"smoke alarm": "smoke detector",
"headboard": "headboard",
"bedpost": "bedframe",
"wall cubby": "shelf",
"toiletry": "toiletry",
"globe stand": "stand",
"swivel chair": "office chair",
"bar soap": "soap",
"sheet": "bed",
"shirt": "shirt",
"coffee mug": "mug",
"toilet seat": "toilet",
"door handle": "door",
"exit sign": "exit sign",
"kitchen wall": "wall",
"washcloth": "washcloth",
"table stand": "stand",
"wall /outside": "wall",
"gym rope": "rope",
"gym equipment": "dumbbell",
"barbell": "dumbbell",
"gym stepper": "stair",
"gym mat": "mat",
"wall beam": "wood beam",
"meshwork": "object",
"punchbag": "bag",
"boxing ring": "structure",
"water tank": "container",
"exercise mat roll": "mat",
"gate": "door",
"trophy": "statue",
"payment terminal": "object",
"cash register": "object",
"power strip": "power strip",
"cloth hanger": "clothes hanger",
"jewelry box": "jewelry box",
"extension cord": "power outlet",
"gramophone": "music stand",
"stereo set": "speaker",
"newspaper basket": "basket",
"phone": "telephone",
"hourglass": "clock",
"cat": "cat litter box",
"balcony railing": "railing",
"bed curtain": "curtain",
"swing": "furniture",
"skateboard": "board",
"cat tree": "furniture",
"laundry": "clothes",
"clothing stand": "clothing rack",
"sink pipe": "pipe",
"trash bag": "trash bag",
"lid": "cover",
"foosball game table": "foosball table",
"workout bike": "exercise machine",
"canvas": "picture",
"cat food": "food container",
"chair /w clutter": "chair",
"wreath": "decoration",
"shade": "curtain",
"wall soap shelf": "soap dish",
"hair brush": "hair brush",
"hair dryer": "hair dryer",
"shower mat": "mat",
"beanbag chair": "beanbag chair",
"yoga mat": "yoga mat",
"computer tower": "computer tower",
"canister": "container",
"motorcycle": "bicycle",
"cabinet /w clutter": "cabinet",
"tire": "tire",
"axe": "toolbox",
"partition": "divider",
"electric wire casing": "power outlet",
"cleaning clutter": "broom",
"shower tray": "shower",
"fuse box": "fuse box",
"mortar": "container",
"soap dish cubby": "soap dish",
"curtain valence": "curtain",
"beanbag": "beanbag chair",
"boxes with books": "boxes",
"wine": "bottle",
"box with books": "box",
"electric heater": "heater",
"hot water/cold water knob": "faucet",
"wall tv": "tv",
"box of something": "box",
"garage door motor": "garage door",
"fuse panel": "electric panel",
"closet storage area": "closet",
"lampshade": "lamp",
"dvd": "object",
"curtain box": "curtain",
"board game": "object",
"easel": "easel",
"blackboard": "blackboard",
"overhang": "structure",
"drainpipe": "pipe",
"grass": "floor",
"patio": "floor",
"wall statue": "statue",
"recessed shelving": "shelf",
"cornice": "wall",
"coat rack": "coat rack",
"candelabra": "chandelier",
"tea set": "cup",
"purse": "purse",
"notes": "paper",
"wall outside": "wall",
"office wall": "wall",
"floor stand": "stand",
"banner": "banner",
"cups": "cups",
"drawer sink table": "sink",
"liquid cleaner": "spray bottle",
"wall panel frame": "frame",
"poster": "poster",
"brochures": "papers",
"calculator": "object",
"pavement": "floor",
"chest drawer": "dresser",
"pen cup": "cup",
"pendant": "object",
"box pen": "box",
"bathtub tap": "bathtub",
"sink tap": "sink",
"sewing box": "box",
"attic hatch": "ceiling",
"shredder": "shredder",
"decor": "decoration",
"board games": "object",
"chess": "object",
"piano bench": "piano bench",
"basket with books": "basket",
"cross": "object",
"kitchen utensils": "kitchen cabinet",
"christmas tree": "decoration",
"containers": "container",
"cans of paint": "can",
"cardboard": "cardboard",
"basketballs": "ball",
"sleeping bag": "sleeping bag",
"cloth hangers": "clothes hanger",
"scoop": "object",
"electrical device": "electric panel",
"chimney": "structure",
"bags": "bag",
"box of food": "box",
"liquid container": "bottle",
"staircase wall": "wall",
"garage door opener railing": "garage door",
"electric wire": "electric panel",
"silicone gun": "object",
"wheel": "wheel",
"drawers": "drawer",
"boards": "board",
"spray": "spray bottle",
"car": "car",
"bicycle helmets": "helmet",
"baseball bat": "object",
"hammock": "object",
"camping chair": "chair",
"poles": "structure",
"saw": "object",
"baskets": "basket",
"watering can": "can",
"football": "ball",
"notebooks": "book",
"shoes on shelf": "shoes",
"clothes on shelf": "clothes",
"rack with shoes": "shoe rack",
"set of hangers": "clothes hanger",
"stack of clothes": "clothes",
"figurine": "object",
"door screen": "door",
"subwoofer": "speaker",
"dish": "plate",
"stack of towels": "towel",
"shower wall cubby": "shower wall",
"stack of shoes": "shoes",
"stack of blankets": "blanket",
"duvet": "blanket",
"stack of pillows": "pillows",
"stack of bags": "bag",
"set of cosmetics": "object",
"detergent bottle": "bottle",
"central heating furnace": "heater",
"set of valves": "pipe",
"closet rod": "closet rod",
"chair stand": "chair",
"bathroom art": "painting",
"ceiling fixture": "ceiling light",
"shower glass": "shower door",
"bath curtain bar": "shower curtain rod",
"bath grab bar": "grab bar",
"mascots": "statue",
"attic entrance": "door",
"shoe shelf": "shoe rack",
"guitar stand": "guitar case",
"keyboard stand": "keyboard piano",
"air vent installation": "vent",
"washing powder": "laundry detergent",
"electric installation": "electric panel",
"tank": "container",
"stack of boxes": "boxes",
"title": "sign",
"dinner chair": "chair",
"cabinet /otherroom": "cabinet",
"plug": "power outlet",
"countertop /otherroom": "counter",
"whiteboard": "whiteboard",
"dishes": "plate",
"flatware": "kitchen cabinet",
"garage light": "ceiling light",
"aquarium": "fish",
"high shelf": "shelf",
"clothes bag": "laundry bag",
"copier machine": "copier",
"partial": "structure",
"stairs skirt": "stairs",
"roomba": "roomba",
"hutch": "cabinet",
"icebox": "refrigerator",
"stack": "stack of chairs",
"wine cabinet": "cabinet",
"plant ornament": "potted plant",
"fireplace mirror": "mirror",
"stand/small table": "end table",
"artwork": "painting",
"leg rest": "footrest",
"counter door": "cabinet door",
"artwork frame": "frame",
"oil lamp": "lamp",
"round chair": "chair",
"violin case": "instrument case",
"folding stand": "folded chair",
"dress": "clothing",
"art/statue": "statue",
"cassette": "cd case",
"clothes container": "clothing rack",
"shelf / cabinet": "shelf",
"gap": "divider",
"alarm controller": "alarm clock",
"wall control": "light switch",
"flush button": "toilet flush button",
"bread bin": "container",
"soundbar": "speaker",
"game board": "board",
"chaise longue": "sofa chair",
"lantern": "lamp",
"glass door": "door",
"shower battery": "shower control valve",
"dispenser": "soap dispenser",
"glass pane": "window",
"basin faucet": "faucet",
"lawn": "plant",
"garden chair": "bench",
"garden bench": "bench",
"sky": "ceiling",
"garden deck": "object",
"ceiling corridor": "ceiling",
"router": "object",
"cleaning spray": "spray bottle",
"elephant sculpture": "statue",
"salt and pepper grinder": "salt",
"projector screen": "projector screen",
"gift": "box",
"typewriter": "keyboard",
"violin": "guitar",
"sheet music": "music book",
"kitchen chair": "chair",
"cabinet drawer": "drawer",
"pitchfork": "object",
"hammer": "toolbox",
"salver": "tray",
"napkin": "towel",
"fork": "knife block",
"apron": "kitchen apron",
"sledge": "object",
"chamber pot": "toilet",
"floor /otherroom": "floor",
"door /otherroom": "door",
"painting /otherroom": "painting",
"window frame /otherroom": "window",
"mannequin": "clothing",
"cloth holder": "clothes hanger",
"storage": "storage box",
"bread": "food container",
"bottom of stairs": "stairs",
"fire pit": "fireplace",
"balcony": "platform",
"night lamp": "lamp",
"bathroom window": "window",
"skirting board": "wall",
"pencil": "pen holder",
"sticky notes": "paper",
"pen": "pen holder",
"spoon": "plate",
"desk organizer": "organizer",
"stapler": "paper",
"flush": "toilet flush button",
"document holder": "file cabinet",
"conference phone": "telephone",
"identifier": "object",
"shower frame": "shower",
"compressor": "machine",
"recuperator": "machine",
"terrace": "platform",
"cook book": "book",
"rocking horse": "object",
"kitchen counter support": "kitchen counter",
"keyboard piano": "piano",
"power breaker box": "electric panel",
"stack of yarns": "storage box",
"den": "object",
"sponge": "washcloth",
"deck chair": "chair",
"torch": "lamp",
"trough": "bucket",
"gutter": "pipe",
"basket of fruits": "basket",
"file": "paper",
"stack of files": "file cabinet",
"shower cockpit": "shower",
"shower mirror": "mirror",
"shower window frame": "window",
"bathroom glass": "mirror",
"circular sofa": "sofa",
"soap dispenser shelf in shower": "soap dispenser",
"recessed cubby": "shelf",
"set of armchairs": "armchair",
"umbrella stand": "stand",
"post": "pillar",
"bed cabinet lamp": "lamp",
"cross-trainer": "exercise machine",
"modem": "machine",
"paper holder": "paper organizer",
"rock": "object",
"bathmat": "mat",
"vanity": "bathroom vanity",
"window /otherroom": "window",
"junk": "trash can",
"decorative mask": "decoration",
"slab": "platform",
"sofa set": "sofa",
"pedestal": "stand",
"display": "monitor",
"lighting fixture": "lamp",
"molding": "wall",
"model": "object",
"niche": "shelf",
"billiard balls": "ball",
"billiard cues": "stick",
"ball pouffe": "seat",
"air freshener": "spray bottle",
"press": "machine",
"pencil holder": "organizer",
"hatch": "door",
"jacuzzi": "bathtub",
"bedding": "bed",
"lounger": "chair",
"salt and pepper": "dispenser",
"kitchen sink cabinet": "sink",
"lighter": "object",
"fur carpet": "carpet",
"bath side table": "end table",
"bell": "object",
"panel screen": "divider",
"fish tank": "container",
"skylight": "window",
"material": "cloth",
"mantle": "shelf",
"note board": "bulletin board",
"cd": "cd case",
"pet bowl": "bowl",
"wall top": "wall",
"pet bed": "bed",
"box with toys": "box",
"cage": "container",
"birdhouse": "decoration",
"box with shoes": "box",
"fluorescent light": "light",
"medical lamp": "lamp",
"paper towels": "towel",
"relief": "object",
"massage bed": "bed",
"hand dryer": "hand dryer",
"makeup accessories": "toiletry",
"double armchair": "armchair",
"bathroom wall": "wall",
"art piece": "painting",
"foot spa": "bathtub",
"spa armchair": "armchair",
"spa bathtub": "bathtub",
"thermometer": "thermostat",
"sauna seat": "seat",
"sauna support": "handrail",
"sauna oven": "oven",
"foam": "sponge",
"beverage dispenser": "water cooler",
"box with tea": "box",
"shelf with cosmetics": "shelf",
"product": "object",
"advertisement": "poster",
"steel plate": "plate",
"electric hub": "power outlet",
"solarium": "structure",
"flush push": "toilet flush button",
"cleaner brush": "broom",
"solarium door": "door",
"bottle dispenser": "dispenser",
"floor vent": "vent",
"staircase": "stairs",
"emergency sign": "exit sign",
"bed base": "bed",
"dehumidifier": "humidifier",
"package": "box",
"cyp": "plant",
"stack of magazines": "magazine",
"stack of binders": "binders",
"planner": "calendar",
"box of paper": "boxes of paper",
"groceries": "food container",
"alcohol bottles": "bottles",
"cookies": "food display",
"kitchenware": "cooking pan",
"bag with something": "bag",
"set of knives": "knife block",
"display of pictures": "pictures",
"toothpaste": "toothpaste",
"toiletry bag": "toiletry",
"sandals": "shoes",
"mobile": "telephone",
"cd player": "cd case",
"breadbox": "storage box",
"electric toothbrush": "toothbrush",
"eyeglasses": "glass",
"art/clutter": "decoration",
"photo stand": "picture",
"records": "music book",
"microphone": "speaker",
"shoe cabinet": "shoe rack",
"dog leash": "object",
"stairwell": "staircase",
"flashlight": "light",
"backsplash": "wall",
"rag": "cloth",
"chaise": "seat",
"shoe rack": "shoe rack",
"playpen": "crib",
"shower cabinet": "shower",
"chain": "chain",
"drill": "object",
"tool rack": "rack",
"cork board": "bulletin board",
"dish dryer": "dish rack",
"hand cloth": "hand towel",
"chest of drawer": "drawer",
"secretary": "desk",
"air hockey": "object",
"medal": "object",
"shower valve": "shower control valve",
"ceiling border": "ceiling",
"toaster oven": "toaster oven",
"foot stand": "footrest",
"closet floor": "floor",
"recliner": "armchair",
"condiment": "salt",
"security detector": "smoke detector",
"porcelain": "vase",
"mail": "mail",
"ceiling panel": "ceiling",
"cleaning fluid": "laundry detergent",
"ceiling lamp rail": "ceiling light",
"medical object": "object",
"electricity box": "electric panel",
"meter": "scale",
"electrical installation": "power outlet",
"pole": "pillar",
"extension lead": "power strip",
"coaster": "mat",
"bonsai tree": "plant",
"window seat": "seat",
"dish rack": "dish rack",
"cradle": "crib",
"tent": "structure",
"headset": "headphones",
"table pad": "table",
"archway": "doorframe",
"box of fruit": "box",
"laundry bag": "laundry bag",
"fireplace brush": "broom",
"pantry": "kitchen cabinet",
"shower case": "shower",
"drawer desk": "desk",
"soft chair": "armchair",
"workstation": "desk",
"moose head/sculpture/hunting trophy": "decoration",
"plane": "airplane",
"storage space": "storage bin",
"cat litter box": "cat litter box",
"separator": "divider",
"bridge": "structure",
"ball pool": "ball",
"stage": "platform",
"curb": "structure",
"sunbed": "couch",
"mailbox": "mailbox",
"exercise ladder": "ladder",
"stones": "structure",
"sauna heat rocks": "structure",
"barbecue": "object",
"bath towels": "towel",
"boat model": "boat",
"copier": "copier",
"bureau": "dresser",
"kitchen sink": "sink",
"bedside cabinet drawer": "drawer",
"bedside cabinet door": "cabinet doors",
"bath carpet": "rug",
"bathroom cabinet drawer": "drawer",
"bathroom cabinet door": "cabinet doors",
"shower base": "shower",
"tennis racket": "tennis racket",
"window/door": "door",
"bathtub knob": "bathtub",
"set of towels": "towels",
"glass container": "container",
"stack of trays": "tray",
"bathroom rug": "rug",
"binders": "binders",
"hole puncher": "stapler",
"stools": "stool",
"mousepad": "keyboard",
"shoe case": "shoe rack",
"screw box": "toolbox",
"electric cord": "power outlet",
"bricks": "structure",
"plenum box": "box",
"water meter": "object",
"gauge": "object",
"gas meter": "object",
"water pump": "machine",
"water outlet": "faucet",
"crutches": "crutches",
"beer crate": "crate",
"bread box": "box",
"electric plug": "power outlet",
"air purifier": "fan",
"bicycle helmet": "helmet",
"extractor hood": "range hood",
"brushes": "toilet brush",
"vegetables": "object",
"waffle iron": "iron",
"bag with sheets": "bag",
"lamp shade": "lamp",
"cat bed": "bed",
"row of theater chairs": "seat",
"rice cooker": "rice cooker",
"blanket basket": "basket",
"blankets": "blanket",
"scanner": "scanner",
"shower utensil": "soap",
"cabinet /w cluttered art": "cabinet",
"place mat": "mat",
"draw": "drawer",
"water fountain": "water fountain",
"aisle frame": "frame",
"box with jewelry": "jewelry box",
"decorative tray": "tray",
"decorative vessel": "vase",
"ceramics": "vase",
"charger": "power outlet",
"wifi router": "object",
"prop": "decoration",
"fishing rod": "rod",
"fitness ball": "exercise ball",
"exercising blocks": "dumbbell",
"drawing": "picture",
"foosball table": "foosball table",
"baseboard": "board",
"gas box": "box",
"stone bench": "bench",
"ceiling fan lamp": "ceiling fan",
"chest bench": "bench",
"fur": "rug",
"shoulder bag": "bag",
"decorative window": "window",
"lace doily": "table",
"bedroom table": "end table",
"blouse": "clothing",
"drawer cabinet": "cabinet",
"dried flowers": "plant",
"decorative frame": "frame",
"box with photos": "box",
"electric device": "power outlet",
"electric freshener": "object",
"fishing pole": "rod",
"vinyl records": "object",
"apple": "object",
"card": "card",
"star": "star",
"ragdoll": "doll",
"doily": "table",
"ragdoll cat": "object",
"pot lid": "pot",
"pouches": "bag",
"gun": "nerf gun",
"handkerchiefs": "cloth",
"training mat": "mat",
"painting roll": "painting",
"painting rolls": "painting",
"painting tray": "painting",
"controller": "controller",
"electrical switchboard": "electric panel",
"glue": "tape",
"measuring tape": "tape",
"ruler": "object",
"wrench": "object",
"pliers": "object",
"screwdriver": "object",
"level": "object",
"spatula": "object",
"square": "object",
"roll": "paper towel roll",
"cans": "can",
"base": "object",
"rods": "rod",
"baseball cap": "cap",
"shade rail": "rail",
"crayon": "object",
"drawer cart": "cart",
"gas furnace": "furnace",
"silicone tube": "tube",
"drywall board": "wall",
"canal": "object",
"cat food bag": "object",
"buckets": "bucket",
"spirit level": "object",
"air heater": "heater",
"trampoline": "object",
"folded table": "folded table",
"hoverboard": "hoverboard",
"kitchen towel": "towel",
"knife stand": "knife block",
"food processor": "kitchen mixer",
"bottle of wine": "bottle",
"frying pan": "frying pan",
"cooker hood": "range hood",
"ball chair": "chair",
"leaflets": "paper",
"strongbox": "chest",
"dog toy": "toy dinosaur",
"console pad": "controller",
"console pad charger": "object",
"console": "media center",
"baby seat": "carseat",
"ceiling floor": "ceiling",
"drawers for clothes": "dresser",
"drinking fountain": "water fountain",
"cone": "traffic cone",
"albums": "cd case",
"sticker book": "book",
"price tag": "object",
"stack of chairs": "stack of chairs",
"magic marker": "pen holder",
"music equipment stand": "music stand",
"electric percussion": "drum set",
"magic marker box": "pen holder",
"ceiling chassis": "ceiling",
"ceiling hanger": "ceiling",
"guitar pedals": "guitar",
"ukulele": "guitar",
"guitar cases": "guitar case",
"guitar case": "guitar case",
"guitar case cover": "guitar case",
"keyboard cover": "keyboard",
"product box": "box",
"stack of product boxes": "boxes",
"board with keys": "keyboard",
"trombone": "instrument case",
"trumpet": "instrument case",
"saxophone": "instrument case",
"clarinet": "instrument case",
"tambourine": "instrument case",
"product boxes": "boxes",
"electric drum": "drum set",
"cabinet counter": "kitchen cabinet",
"counter desk": "desk",
"album": "book",
"stack of albums": "stack of chairs",
"shop shelf": "shelf",
"microphone accessory": "music stand",
"audio cable": "power outlet",
"audio cables": "power strip",
"guitar straps": "guitar case",
"t-shirt": "clothing",
"stack of t-shirts": "stacks of cups",
"socks": "sock",
"products": "container",
"keyboard box": "keyboard piano",
"stack of music stands": "stack of chairs",
"round cushion": "pillow",
"tripod": "tripod",
"baby chair": "armchair",
"shoes rack": "shoe rack",
"acoustic panel": "divider",
"sauna": "shower",
"game": "board",
"electronics": "computer tower",
"music equipment": "keyboard piano",
"bunk bed": "bunk bed",
"stack of plates": "plates",
"antlers": "statue",
"menu board": "board",
"jars": "jar",
"menu": "board",
"cleaner bottle": "spray bottle",
"receipt printer": "printer",
"sombrero": "hat",
"shisha": "pipe",
"keg": "container",
"saturator": "humidifier",
"gas container": "container",
"spices": "salt",
"receipt spike": "paper",
"spray can": "spray bottle",
"bowls": "bowl",
"bottle opener": "bottle",
"gloves": "clothing",
"stovetop": "stovetop"
}
