RSCAN_SCANNET = {
'pillow': 'pillow',
'box': 'box',
'item': 'object',
'curtain': 'curtain',
'towel': 'towel',
'garbage bin': 'trash bin',
'wall': 'wall',
'floor': 'floor',
'figure': 'statue',
'frame': 'frame',
'shelf': 'shelf',
'clothes': 'clothing',
'picture': 'picture',
'organizer': 'organizer shelf',
'ceiling': 'ceiling',
'object': 'object',
'cabinet': 'cabinet',
'blanket': 'blanket',
'monitor': 'monitor',
'door': 'door',
'roll': 'paper towel roll',
'bed': 'bed',
'desk': 'desk',
'window': 'window',
'nightstand': 'nightstand',
'rack': 'rack stand',
'plant': 'potted plant',
'cushion': 'cushion',
'light': 'light',
'table': 'table',
'windowsill': 'windowsill',
'shades': 'blinds',
'sofa': 'sofa',
'beanbag': 'beanbag chair',
'commode': 'toilet',
'heater': 'heater',
'trash can': 'trash can',
'child chair': 'stool',
'mirror': 'mirror',
'lamp': 'lamp',
'sink': 'sink',
'cupboard': 'kitchen cabinet',
'toilet paper': 'toilet paper rolls',
'toilet': 'toilet',
'handhold': 'hand rail',
'vase': 'vase',
'toilet brush': 'toilet brush',
'armchair': 'armchair',
'doorframe': 'doorframe',
'bathtub': 'bathtub',
'bath cabinet': 'bathroom cabinet',
'basket': 'basket',
'shower curtain': 'shower curtain',
'bin': 'trash bin',
'kitchen hood': 'range hood',
'kitchen cabinet': 'kitchen cabinet',
'kitchen sofa': 'sofa',
'chair': 'chair',
'rag': 'towel',
'kitchen counter': 'kitchen counter',
'oven': 'oven',
'microwave': 'microwave',
'fruit plate': 'plate',
'player': 'keyboard piano',
'kitchen appliance': 'microwave',
'kettle': 'kettle',
'wardrobe': 'wardrobe closet',
'stool': 'stool',
'stand': 'stand',
'shoes': 'shoes',
'counter': 'counter',
'hand dryer': 'hand dryer',
'suitcase': 'suitcase',
'closet': 'closet',
'tv': 'tv',
'bag': 'bag',
'laptop': 'laptop',
'jalousie': 'blinds',
'whiteboard': 'whiteboard',
'planter': 'flowerpot',
'shower': 'shower',
'hanging cabinet': 'kitchen cabinets',
'flower': 'plant',
'washbasin': 'sink',
'clothes dryer': 'clothes dryers',
'sack': 'bag',
'basin': 'sink',
'radiator': 'radiator',
'refrigerator': 'refrigerator',
'clutter': 'object',
'vacuum cleaner': 'vacuum cleaner',
'shelf unit': 'shelf',
'mop': 'broom',
'ironing board': 'ironing board',
'iron': 'iron',
'bucket': 'bucket',
'toy': 'doll',
'stairs': 'stairs',
'barrel': 'container',
'washing machine': 'washing machine',
'carpet': 'carpet',
'sidecouch': 'couch',
'tv stand': 'tv stand',
'bench': 'bench',
'humidifier': 'humidifier',
'hanger': 'clothes hanger',
'backpack': 'backpack',
'drawer': 'drawer',
'console': 'computer tower',
'hangers': 'clothes hanger',
'blinds': 'blinds',
'balcony door': 'door',
'upholstered wall': 'wall',
'coffee table': 'coffee table',
'blackboard': 'blackboard',
'glass wall': 'window',
'bottles': 'bottle',
'pack': 'bag',
'scale': 'scale',
'ventilation': 'fan',
'paper towel': 'paper towel roll',
'bottle': 'bottle',
'dish dryer': 'dish rack',
'candle': 'candle',
'pc': 'computer tower',
'washing': 'washing machine',
'tube': 'tube',
'snowboard': 'board',
'board': 'board',
'pipe': 'pipe',
'water heater': 'water heater',
'vacuum': 'vacuum cleaner',
'stuffed animal': 'stuffed animal',
'decoration': 'decoration',
'shower wall': 'shower wall',
'telephone': 'telephone',
'plate': 'plate',
'watering can': 'can',
'device': 'object',
'stove': 'stove',
'kitchen towel': 'towel',
'garbage': 'trash can',
'shampoo': 'shampoo bottle',
'statue': 'statue',
'shower door': 'shower door',
'book': 'book',
'fan': 'fan',
'speaker': 'speaker',
'pile of books': 'books',
'side table': 'end table',
'table lamp': 'table lamp',
'couch': 'couch',
'magazine': 'magazine',
'papers': 'papers',
'books': 'books',
'furniture': 'furniture',
'magazine files': 'magazine rack',
'mannequin': 'object',
'boxes': 'boxes',
'clock': 'clock',
'cube': 'object',
'napkins': 'cloth',
'stuffed': 'stuffed animal',
'luggage': 'luggage',
'partition': 'divider',
'trash': 'trash can',
'coffee': 'coffee maker',
'bar': 'bar',
'newspaper': 'paper',
'wood': 'wood',
'fireplace': 'fireplace',
'dining': 'dining table',
'dining table': 'dining table',
'bread': 'object',
'fruits': 'object',
'kitchen': 'kitchen cabinet',
'can': 'can',
'squeezer': 'object',
'bowl': 'bowl',
'recycle': 'recycling bin',
'barstool': 'stool',
'computer': 'computer tower',
'umbrella': 'umbrella',
'bath': 'bathtub',
'hanging': 'hanging',
'rocking': 'object',
'objects': 'object',
'flowers': 'plant',
'plants': 'plant',
'jar': 'jar',
'bedside': 'nightstand',
'buggy': 'object',
'side': 'object',
'socket': 'power outlet',
'showcase': 'display case',
'drying': 'drying rack',
'ottoman': 'ottoman',
'pictures': 'pictures',
'storage': 'storage bin',
'footstool': 'footstool',
'folding': 'folded chair',
'ladder': 'ladder',
'shoe': 'shoes',
'pet': 'object',
'medical': 'object',
'soap': 'soap',
'balcony': 'object',
'foosball': 'foosball table',
'hand': 'object',
'bookshelf': 'bookshelf',
'pile': 'object',
'cleaning': 'object',
'flush': 'toilet flush button',
'towels': 'towels',
'candlestick': 'candle',
'puf': 'object',
'printer': 'printer',
'shelves': 'shelf',
'stair': 'stair',
'cleanser': 'soap bottle',
'armoire': 'wardrobe closet',
'bidet': 'object',
'exit': 'exit sign',
'toaster': 'toaster',
'laundry': 'laundry basket',
'hood': 'range hood',
'sponge': 'sponge',
'fridge': 'refrigerator',
'breadboard': 'cutting board',
'pan': 'frying pan',
'water': 'water bottle',
'teapot': 'tea kettle',
'projector': 'projector',
'juicer': 'kitchen mixer',
'cutting': 'cutting board',
'windows': 'windowsill',
'food': 'food container',
'cup': 'cup',
'rug': 'rug',
'column': 'column',
'keyboard': 'keyboard',
'office': 'office chair',
'exhaust': 'range hood',
'apron': 'kitchen apron',
'pepper': 'salt',
'knife': 'knife block',
'cooking': 'cooking pot',
'tablet': 'ipad',
'bicycle': 'bicycle',
'pillar': 'pillar',
'machine': 'washing machine',
'meter': 'scale',
'cut': 'paper cutter',
'salt': 'salt',
'candles': 'candle',
'grass': 'plant',
'sidetable': 'end table',
'sewing': 'sewing machine',
'guitar': 'guitar',
'flag': 'flag',
'paper': 'paper',
'sugar': 'bowl',
'cups': 'cups',
'packs': 'boxes',
'plates': 'plates',
'tray': 'tray',
'chandelier': 'chandelier',
'mandarins': 'bananas',
'puppet': 'doll',
'painting': 'painting',
'cradle': 'crib',
'price': 'tag',
'dish': 'dish rack',
'boiler': 'boiler',
'fruit': 'bananas',
'multicooker': 'rice cooker',
'items': 'object',
'extractor': 'juicer',
'air': 'fan',
'dressing': 'mirror',
'round': 'round table',
'screen': 'screen',
'mattress': 'mattress',
'bike': 'bicycle',
'rolled': 'rolled poster',
'locker': 'cabinet',
'tennis': 'tennis racket',
'cap': 'cap',
'ball': 'ball',
'folder': 'folder',
'milk': 'refridgerator',
'dishdrainer': 'dish rack',
'dishwasher': 'dishwasher',
'piano': 'piano',
'stereo': 'speaker',
'upholstered': 'couch',
'folded': 'folded chairs',
'loft': 'loft bed',
'aquarium': 'fish',
'dispenser': 'soap dispenser',
'body': 'person',
'sign': 'sign',
'baby': 'crib',
'chest': 'chest',
'pot': 'pot',
'drawers': 'drawer',
'rail': 'rail',
'platform': 'platform',
'tree': 'plant',
'armor': 'helmet',
'ironing': 'ironing board',
'headboard': 'headboard',
'crib': 'crib',
'beverage': 'bottle',
'plank': 'wood',
'generator': 'machine',
'file': 'file cabinet',
'coat': 'coat rack',
'tool': 'toolbox',
'rolling': 'cart',
'tire': 'tire',
'cable': 'cable',
'fence': 'gate',
'handrail': 'handrail',
't-shirt': 'shirt',
'ramp': 'stairs',
'seat': 'seat',
'sideboard': 'cabinet',
'lounger': 'chair',
'discs': 'cd case',
'drum': 'drum set',
'drinks': 'soda can',
'chairs': 'chair',
'dishes': 'dish rack',
'linen': 'towel',
'glass': 'glass',
'xbox': 'xbox controller',
'ukulele': 'guitar',
'pin': 'needle'
}
