# Experiment general info
name: "3DX_reproduce"
rng_seed: 42
num_gpu: 2
mode: "train"
note: ""
# Choose keywords to feature your saving directory
naming_keywords: ["dataloader.batchsize", "task", "note", "time"]
base_dir: "/scratch/masaccio/results"
exp_dir: ""
save_frequency: 10

resume: False

debug:
  flag: False
  debug_size: 20

logger:
  name: "wandb"
  entity: "buzz-beater"

# dataset details
data:
  use_voxel: True
  pretrain: 
    dataset: ['RScan', 'ScanNet']
    scan_caption: ["scanrefer", "referit3d", "scanqa"]
    rscan_caption: ["template", "gpt"]
    args:
      tokenizer: bert_tokenizer
      max_seq_len: 50
      max_obj_len: 80
      num_points: 1024
      mask_strategy: random
      txt_mask_ratio: 0.15
      pc_mask_ratio: 0.1
      pc_type: 'gt'
  scanrefer:
    dataset: ['ScanNet']
    args:
      max_obj_len: 60
      max_seq_len: 80
      num_points: 1024
      pc_type: 'gt'
      sem_type: '607'
      filter_lang: False
  referit3d:
    dataset: ['ScanNet']
    args:
      max_obj_len: 60
      max_seq_len: 80
      num_points: 1024
      pc_type: 'gt'
      sem_type: '607'
      filter_lang: False
      anno_type: 'nr3d' # 'nr3d', 'sr3d'
      sr3d_plus_aug: False
  scanqa:
    dataset: ['ScanNet']
    args:
      max_obj_len: 60
      max_seq_len: 80
      num_points: 1024
      pc_type: 'gt'
      sem_type: '607'
      filter_lang: False
      use_unanswer: True

  scan_family_base: "/scratch/masaccio/existing_datasets/scannet"
  rscan_base: "/scratch/masaccio/existing_datasets/3RScan-base"
  nmr_base: "/scratch/massaccio/existing_datasets/nmr"

# dataloader details
dataloader:
  # This is a per-gpu batchsize
  batchsize: 32
  num_workers: 2
  balance_dataset: False
  filter_empty_annotations: False

# task details: 'pretrain', 'scanrefer', 'referit3d', 'scanqa', 'default'
task: 'Pretrain'

# Training details
trainer: "DefaultTrainer"
ckpt_path: ""
pretrain_ckpt_path: ""

solver:
  gradient_accumulation_steps: 1
  lr: 1e-4
  grad_norm: 5.0
  epochs: 100
  optim:
    name: "AdamW"
    args:
      betas: [0.9, 0.98]
  sched:
    name: "warmup_cosine"
    args:
      warmup_steps: 5000

eval:
  name: "PretrainEval"
  save: True

# Model details
model:
  name: Vista3D
  language:
    # This part could be further optimized to be using
    # huggingface yaml config files
    name: "BERTLanguageEncoder"
    args:
      weights: "bert-base-uncased"
      hidden_size: 768
      num_hidden_layers: 3
      num_attention_heads: 12
      type_vocab_size: 2
    lr: 1e-5
  vision:
#    name: "pointnet_point_encoder"
#    args:
#      path: None
#      freeze: False
    name: "PointTokenizeEncoder"
    args:
        backbone: "pointnet++"
        hidden_size: 768
        freeze: True
        path: "/scratch/masaccio/code/pretrained_weights/pointnet_tokenizer.pth"
        num_attention_heads: 12
        spatial_dim: 5
        num_layers: 4
        dim_loc: 6
        pairwise_rel_type: "center"
        use_matmul_label: False
        glove_path: "/scratch/masaccio/existing_datasets/scannet"
    lr: 1e-4
  grounding:
    name: "UnifiedSpatialCrossEncoderV2"
    args:
      hidden_size: 768
      num_attention_heads: 12
      num_layers: 4
      dim_loc: 6
    lr: 1e-4
  heads:
    head_list: ["pretrain_head", "qa_head", "ground_head"]
    pretrain_head:
      name: "PretrainHeadV1"
      args:
        hidden_size: 768
        vocab_size: 30522
    ground_head:
      name: "GroundHeadV1"
      args:
        hidden_size: 384
        input_size: 768
        sem_cls_size: 607
        dropout: 0.3
        detach_all_aux_loss: False
    qa_head:
      name: "QAHeadV1"
      args:
        hidden_size: 768
        mlp_size: 256
        glimpse: 1
        flat_out_size: 512
        num_answers: 8864
  loss_type: "ListLoss"
  loss_list: [
      "lm_cls_loss", "obj_cls_raw_loss", "obj_cls_pre_loss",
      "obj_cls_post_loss"
  ]
  vis_loss_list: [
      "lm_cls_loss", "obj_cls_raw_loss", "obj_cls_pre_loss",
      "obj_cls_post_loss", "obj_cls_pre_loss_mask",
      "obj_cls_pre_loss_unmask", "obj_cls_post_loss_mask",
      "obj_cls_post_loss_unmask"
  ]
